### PR TITLE
Fix: ping station2station from diferents networks

### LINKED ISSUE #15: Configure IPv4 Addresses
Configurar Direcciones IPv4 en las interfaces RingLink que no sean localhost.
Actualmente tenemos 127.0.0.X como direcciones IP de las interfaces RingLink. 
Se necesita configurar direcciones como fue acordado con IPs privadas 192.168.1.X

### LINKED ISSUE #18: Improve Wi-Fi interface

### PR DESCRIPTION
**Pull request by quiroga-juan**

### CODE REVIEW

**Review by changeemma — APPROVED** [review]

File: components/ring_link/include/ring_link.h [hunk 1]
```diff
@@ -8,6 +8,8 @@
 extern "C" {
 #endif
 
+#define RING_LINK_MEM_TASK 16384
```
Comment (changeemma) [inline components/ring_link/include/ring_link.h:11]: nit: I would suggest naming it `RING_LINK_TASK_MEM`

**Comment by changeemma** [comment]
fixes https://github.com/changeemma/esp32-internet-for-all/issues/15
